version: "3"
services:
  proxy:
    build: ./proxy
    environment:
      PORT: "3001"
  ui:
    build: ./ui
    ports:
      - "80:3000"
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      POSTGRESS_CONNECTION_STRING: "host=db user=crudwizard password=crudwizard dbname=crudwizard sslmode=disable"
    depends_on:
      - "db"
  db:
    image: postgres
    environment:
      POSTGRES_USER: crudwizard
      POSTGRES_DB: crudwizard
      POSTGRES_PASSWORD: crudwizard
    ports:
      - "5432:5432"