version: "3"
services:
  web:
    build: ./src-ui
    ports:
      - "3000:80"
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      POSTGRESS_CONNECTION_STRING: "host=db user=crudwizard password=crudwizard dbname=crudwizard sslmode=disable"
    depends_on:
      - "db"
  db:
    image: postgres
    environment:
      POSTGRES_USER: crudwizard
      POSTGRES_DB: crudwizard
      POSTGRES_PASSWORD: crudwizard
    ports:
      - "5432:5432"